//
//  DungGine.h
//  DungGine
//
//  Created by Rasmus Anthin on 2024-06-13.
//

#pragma once
#include "BSPTree.h"


namespace dung
{


  class DungGine
  {
    BSPTree* m_bsp_tree;
    std::vector<BSPNode*> m_leaves;
    
    using WallType = drawing::OutlineType; //{ Hash, Masonry, Masonry1, Masonry2, Masonry3, Temple };
    enum class WallBasicType { Masonry, Temple, Other };
    using ShadowType = drawing::ShadowType;
    using Style = styles::Style;
    enum class FloorType { None, Sand, Grass, Stone, Stone2, Water, Wood, NUM_ITEMS };
    
    class RoomStyle
    {
      static inline std::map<WallBasicType, std::vector<Style>> wall_palette
      {
        { WallBasicType::Masonry,
          {
            { Text::Color::Black, Text::Color::Black },
            { Text::Color::Black, Text::Color::DarkRed },
            { Text::Color::Black, Text::Color::DarkGreen },
            { Text::Color::Black, Text::Color::DarkYellow },
            { Text::Color::Black, Text::Color::DarkBlue },
            { Text::Color::Black, Text::Color::DarkMagenta },
            { Text::Color::Black, Text::Color::DarkCyan },
            { Text::Color::Black, Text::Color::LightGray },
            { Text::Color::Black, Text::Color::DarkGray },
            { Text::Color::Black, Text::Color::Red },
            { Text::Color::Black, Text::Color::Green },
            { Text::Color::Black, Text::Color::Yellow },
            { Text::Color::Black, Text::Color::Blue },
            { Text::Color::Black, Text::Color::Magenta },
            { Text::Color::Black, Text::Color::Cyan },
            { Text::Color::Black, Text::Color::White },
            { Text::Color::DarkRed, Text::Color::Black },
            { Text::Color::DarkRed, Text::Color::DarkRed },
            { Text::Color::DarkRed, Text::Color::DarkGreen },
            { Text::Color::DarkRed, Text::Color::DarkYellow },
            //{ Text::Color::DarkRed, Text::Color::DarkBlue },
            { Text::Color::DarkRed, Text::Color::DarkMagenta },
            { Text::Color::DarkRed, Text::Color::DarkCyan },
            { Text::Color::DarkRed, Text::Color::LightGray },
            { Text::Color::DarkRed, Text::Color::DarkGray },
            { Text::Color::DarkRed, Text::Color::Red },
            { Text::Color::DarkRed, Text::Color::Green },
            { Text::Color::DarkRed, Text::Color::Yellow },
            { Text::Color::DarkRed, Text::Color::Blue },
            { Text::Color::DarkRed, Text::Color::Magenta },
            { Text::Color::DarkRed, Text::Color::Cyan },
            { Text::Color::DarkRed, Text::Color::White },
            { Text::Color::DarkGreen, Text::Color::Black },
            { Text::Color::DarkGreen, Text::Color::DarkRed },
            { Text::Color::DarkGreen, Text::Color::DarkGreen },
            { Text::Color::DarkGreen, Text::Color::DarkYellow },
            { Text::Color::DarkGreen, Text::Color::DarkBlue },
            { Text::Color::DarkGreen, Text::Color::DarkMagenta },
            { Text::Color::DarkGreen, Text::Color::DarkCyan },
            { Text::Color::DarkGreen, Text::Color::LightGray },
            { Text::Color::DarkGreen, Text::Color::DarkGray },
            { Text::Color::DarkGreen, Text::Color::Red },
            { Text::Color::DarkGreen, Text::Color::Green },
            { Text::Color::DarkGreen, Text::Color::Yellow },
            { Text::Color::DarkGreen, Text::Color::Blue },
            { Text::Color::DarkGreen, Text::Color::Magenta },
            { Text::Color::DarkGreen, Text::Color::Cyan },
            { Text::Color::DarkGreen, Text::Color::White },
            { Text::Color::DarkYellow, Text::Color::Black },
            { Text::Color::DarkYellow, Text::Color::DarkRed },
            { Text::Color::DarkYellow, Text::Color::DarkGreen },
            { Text::Color::DarkYellow, Text::Color::DarkYellow },
            { Text::Color::DarkYellow, Text::Color::DarkBlue },
            { Text::Color::DarkYellow, Text::Color::DarkMagenta },
            { Text::Color::DarkYellow, Text::Color::DarkCyan },
            { Text::Color::DarkYellow, Text::Color::LightGray },
            { Text::Color::DarkYellow, Text::Color::DarkGray },
            { Text::Color::DarkYellow, Text::Color::Red },
            { Text::Color::DarkYellow, Text::Color::Green },
            { Text::Color::DarkYellow, Text::Color::Yellow },
            { Text::Color::DarkYellow, Text::Color::Blue },
            { Text::Color::DarkYellow, Text::Color::Magenta },
            { Text::Color::DarkYellow, Text::Color::Cyan },
            { Text::Color::DarkYellow, Text::Color::White },
            { Text::Color::DarkBlue, Text::Color::Black },
            { Text::Color::DarkBlue, Text::Color::DarkRed },
            { Text::Color::DarkBlue, Text::Color::DarkGreen },
            { Text::Color::DarkBlue, Text::Color::DarkYellow },
            { Text::Color::DarkBlue, Text::Color::DarkBlue },
            { Text::Color::DarkBlue, Text::Color::DarkMagenta },
            { Text::Color::DarkBlue, Text::Color::DarkCyan },
            { Text::Color::DarkBlue, Text::Color::LightGray },
            { Text::Color::DarkBlue, Text::Color::DarkGray },
            { Text::Color::DarkBlue, Text::Color::Red },
            { Text::Color::DarkBlue, Text::Color::Green },
            { Text::Color::DarkBlue, Text::Color::Yellow },
            { Text::Color::DarkBlue, Text::Color::Blue },
            { Text::Color::DarkBlue, Text::Color::Magenta },
            { Text::Color::DarkBlue, Text::Color::Cyan },
            { Text::Color::DarkBlue, Text::Color::White },
            { Text::Color::DarkMagenta, Text::Color::Black },
            { Text::Color::DarkMagenta, Text::Color::DarkRed },
            { Text::Color::DarkMagenta, Text::Color::DarkGreen },
            { Text::Color::DarkMagenta, Text::Color::DarkYellow },
            { Text::Color::DarkMagenta, Text::Color::DarkBlue },
            //{ Text::Color::DarkMagenta, Text::Color::DarkMagenta },
            { Text::Color::DarkMagenta, Text::Color::DarkCyan },
            { Text::Color::DarkMagenta, Text::Color::LightGray },
            { Text::Color::DarkMagenta, Text::Color::DarkGray },
            { Text::Color::DarkMagenta, Text::Color::Red },
            { Text::Color::DarkMagenta, Text::Color::Green },
            { Text::Color::DarkMagenta, Text::Color::Yellow },
            { Text::Color::DarkMagenta, Text::Color::Blue },
            //{ Text::Color::DarkMagenta, Text::Color::Magenta },
            { Text::Color::DarkMagenta, Text::Color::Cyan },
            { Text::Color::DarkMagenta, Text::Color::White },
            { Text::Color::DarkCyan, Text::Color::Black },
            { Text::Color::DarkCyan, Text::Color::DarkRed },
            { Text::Color::DarkCyan, Text::Color::DarkGreen },
            { Text::Color::DarkCyan, Text::Color::DarkYellow },
            { Text::Color::DarkCyan, Text::Color::DarkBlue },
            { Text::Color::DarkCyan, Text::Color::DarkMagenta },
            { Text::Color::DarkCyan, Text::Color::DarkCyan },
            { Text::Color::DarkCyan, Text::Color::LightGray },
            { Text::Color::DarkCyan, Text::Color::DarkGray },
            { Text::Color::DarkCyan, Text::Color::Red },
            { Text::Color::DarkCyan, Text::Color::Green },
            { Text::Color::DarkCyan, Text::Color::Yellow },
            { Text::Color::DarkCyan, Text::Color::Blue },
            { Text::Color::DarkCyan, Text::Color::Magenta },
            { Text::Color::DarkCyan, Text::Color::Cyan },
            { Text::Color::DarkCyan, Text::Color::White },
            { Text::Color::LightGray, Text::Color::Black },
            { Text::Color::LightGray, Text::Color::DarkRed },
            { Text::Color::LightGray, Text::Color::DarkGreen },
            { Text::Color::LightGray, Text::Color::DarkYellow },
            { Text::Color::LightGray, Text::Color::DarkBlue },
            { Text::Color::LightGray, Text::Color::DarkMagenta },
            { Text::Color::LightGray, Text::Color::DarkCyan },
            { Text::Color::LightGray, Text::Color::LightGray },
            { Text::Color::LightGray, Text::Color::DarkGray },
            { Text::Color::LightGray, Text::Color::Red },
            { Text::Color::LightGray, Text::Color::Green },
            { Text::Color::LightGray, Text::Color::Yellow },
            { Text::Color::LightGray, Text::Color::Blue },
            //{ Text::Color::LightGray, Text::Color::Magenta },
            { Text::Color::LightGray, Text::Color::Cyan },
            { Text::Color::LightGray, Text::Color::White },
            { Text::Color::DarkGray, Text::Color::Black },
            { Text::Color::DarkGray, Text::Color::DarkRed },
            { Text::Color::DarkGray, Text::Color::DarkGreen },
            { Text::Color::DarkGray, Text::Color::DarkYellow },
            { Text::Color::DarkGray, Text::Color::DarkBlue },
            { Text::Color::DarkGray, Text::Color::DarkMagenta },
            { Text::Color::DarkGray, Text::Color::DarkCyan },
            { Text::Color::DarkGray, Text::Color::LightGray },
            { Text::Color::DarkGray, Text::Color::DarkGray },
            { Text::Color::DarkGray, Text::Color::Red },
            { Text::Color::DarkGray, Text::Color::Green },
            { Text::Color::DarkGray, Text::Color::Yellow },
            { Text::Color::DarkGray, Text::Color::Blue },
            { Text::Color::DarkGray, Text::Color::Magenta },
            { Text::Color::DarkGray, Text::Color::Cyan },
            { Text::Color::DarkGray, Text::Color::White },
            { Text::Color::Red, Text::Color::Black },
            { Text::Color::Red, Text::Color::DarkRed },
            { Text::Color::Red, Text::Color::DarkGreen },
            { Text::Color::Red, Text::Color::DarkYellow },
            //{ Text::Color::Red, Text::Color::DarkBlue },
            { Text::Color::Red, Text::Color::DarkMagenta },
            { Text::Color::Red, Text::Color::DarkCyan },
            { Text::Color::Red, Text::Color::LightGray },
            { Text::Color::Red, Text::Color::DarkGray },
            { Text::Color::Red, Text::Color::Red },
            { Text::Color::Red, Text::Color::Green },
            { Text::Color::Red, Text::Color::Yellow },
            { Text::Color::Red, Text::Color::Blue },
            { Text::Color::Red, Text::Color::Magenta },
            { Text::Color::Red, Text::Color::Cyan },
            { Text::Color::Red, Text::Color::White },
            { Text::Color::Green, Text::Color::Black },
            { Text::Color::Green, Text::Color::DarkRed },
            //{ Text::Color::Green, Text::Color::DarkGreen },
            { Text::Color::Green, Text::Color::DarkYellow },
            { Text::Color::Green, Text::Color::DarkBlue },
            { Text::Color::Green, Text::Color::DarkMagenta },
            { Text::Color::Green, Text::Color::DarkCyan },
            { Text::Color::Green, Text::Color::LightGray },
            { Text::Color::Green, Text::Color::DarkGray },
            { Text::Color::Green, Text::Color::Red },
            { Text::Color::Green, Text::Color::Green },
            { Text::Color::Green, Text::Color::Yellow },
            { Text::Color::Green, Text::Color::Blue },
            { Text::Color::Green, Text::Color::Magenta },
            { Text::Color::Green, Text::Color::Cyan },
            { Text::Color::Green, Text::Color::White },
            { Text::Color::Yellow, Text::Color::Black },
            { Text::Color::Yellow, Text::Color::DarkRed },
            { Text::Color::Yellow, Text::Color::DarkGreen },
            { Text::Color::Yellow, Text::Color::DarkYellow },
            { Text::Color::Yellow, Text::Color::DarkBlue },
            { Text::Color::Yellow, Text::Color::DarkMagenta },
            { Text::Color::Yellow, Text::Color::DarkCyan },
            { Text::Color::Yellow, Text::Color::LightGray },
            { Text::Color::Yellow, Text::Color::DarkGray },
            { Text::Color::Yellow, Text::Color::Red },
            { Text::Color::Yellow, Text::Color::Green },
            { Text::Color::Yellow, Text::Color::Yellow },
            { Text::Color::Yellow, Text::Color::Blue },
            { Text::Color::Yellow, Text::Color::Magenta },
            { Text::Color::Yellow, Text::Color::Cyan },
            { Text::Color::Yellow, Text::Color::White },
            { Text::Color::Blue, Text::Color::Black },
            { Text::Color::Blue, Text::Color::DarkRed },
            { Text::Color::Blue, Text::Color::DarkGreen },
            { Text::Color::Blue, Text::Color::DarkYellow },
            { Text::Color::Blue, Text::Color::DarkBlue },
            { Text::Color::Blue, Text::Color::DarkMagenta },
            { Text::Color::Blue, Text::Color::DarkCyan },
            { Text::Color::Blue, Text::Color::LightGray },
            { Text::Color::Blue, Text::Color::DarkGray },
            { Text::Color::Blue, Text::Color::Red },
            { Text::Color::Blue, Text::Color::Green },
            { Text::Color::Blue, Text::Color::Yellow },
            { Text::Color::Blue, Text::Color::Blue },
            { Text::Color::Blue, Text::Color::Magenta },
            { Text::Color::Blue, Text::Color::Cyan },
            { Text::Color::Blue, Text::Color::White },
            { Text::Color::Magenta, Text::Color::Black },
            { Text::Color::Magenta, Text::Color::DarkRed },
            { Text::Color::Magenta, Text::Color::DarkGreen },
            { Text::Color::Magenta, Text::Color::DarkYellow },
            { Text::Color::Magenta, Text::Color::DarkBlue },
            { Text::Color::Magenta, Text::Color::DarkMagenta },
            { Text::Color::Magenta, Text::Color::DarkCyan },
            { Text::Color::Magenta, Text::Color::LightGray },
            { Text::Color::Magenta, Text::Color::DarkGray },
            { Text::Color::Magenta, Text::Color::Red },
            { Text::Color::Magenta, Text::Color::Green },
            { Text::Color::Magenta, Text::Color::Yellow },
            { Text::Color::Magenta, Text::Color::Blue },
            { Text::Color::Magenta, Text::Color::Magenta },
            { Text::Color::Magenta, Text::Color::Cyan },
            { Text::Color::Magenta, Text::Color::White },
            { Text::Color::Cyan, Text::Color::Black },
            { Text::Color::Cyan, Text::Color::DarkRed },
            { Text::Color::Cyan, Text::Color::DarkGreen },
            { Text::Color::Cyan, Text::Color::DarkYellow },
            { Text::Color::Cyan, Text::Color::DarkBlue },
            { Text::Color::Cyan, Text::Color::DarkMagenta },
            { Text::Color::Cyan, Text::Color::DarkCyan },
            { Text::Color::Cyan, Text::Color::LightGray },
            { Text::Color::Cyan, Text::Color::DarkGray },
            //{ Text::Color::Cyan, Text::Color::Red },
            { Text::Color::Cyan, Text::Color::Green },
            { Text::Color::Cyan, Text::Color::Yellow },
            { Text::Color::Cyan, Text::Color::Blue },
            //{ Text::Color::Cyan, Text::Color::Magenta },
            { Text::Color::Cyan, Text::Color::Cyan },
            { Text::Color::Cyan, Text::Color::White },
            { Text::Color::White, Text::Color::Black },
            { Text::Color::White, Text::Color::DarkRed },
            { Text::Color::White, Text::Color::DarkGreen },
            { Text::Color::White, Text::Color::DarkYellow },
            { Text::Color::White, Text::Color::DarkBlue },
            { Text::Color::White, Text::Color::DarkMagenta },
            { Text::Color::White, Text::Color::DarkCyan },
            { Text::Color::White, Text::Color::LightGray },
            { Text::Color::White, Text::Color::DarkGray },
            { Text::Color::White, Text::Color::Red },
            { Text::Color::White, Text::Color::Green },
            { Text::Color::White, Text::Color::Yellow },
            { Text::Color::White, Text::Color::Blue },
            { Text::Color::White, Text::Color::Magenta },
            { Text::Color::White, Text::Color::Cyan },
            { Text::Color::White, Text::Color::White },
          }
        },
        { WallBasicType::Temple,
          {
            { Text::Color::Black, Text::Color::Black },
            { Text::Color::Black, Text::Color::DarkRed },
            { Text::Color::Black, Text::Color::DarkGreen },
            { Text::Color::Black, Text::Color::DarkYellow },
            { Text::Color::Black, Text::Color::DarkBlue },
            { Text::Color::Black, Text::Color::DarkMagenta },
            { Text::Color::Black, Text::Color::DarkCyan },
            { Text::Color::Black, Text::Color::LightGray },
            { Text::Color::Black, Text::Color::DarkGray },
            { Text::Color::Black, Text::Color::Red },
            { Text::Color::Black, Text::Color::Green },
            { Text::Color::Black, Text::Color::Yellow },
            { Text::Color::Black, Text::Color::Blue },
            { Text::Color::Black, Text::Color::Magenta },
            { Text::Color::Black, Text::Color::Cyan },
            { Text::Color::Black, Text::Color::White },
            { Text::Color::DarkRed, Text::Color::Black },
            { Text::Color::DarkRed, Text::Color::DarkRed },
            { Text::Color::DarkRed, Text::Color::DarkGreen },
            { Text::Color::DarkRed, Text::Color::DarkYellow },
            { Text::Color::DarkRed, Text::Color::DarkBlue },
            { Text::Color::DarkRed, Text::Color::DarkMagenta },
            { Text::Color::DarkRed, Text::Color::DarkCyan },
            { Text::Color::DarkRed, Text::Color::LightGray },
            { Text::Color::DarkRed, Text::Color::DarkGray },
            { Text::Color::DarkRed, Text::Color::Red },
            { Text::Color::DarkRed, Text::Color::Green },
            { Text::Color::DarkRed, Text::Color::Yellow },
            { Text::Color::DarkRed, Text::Color::Blue },
            { Text::Color::DarkRed, Text::Color::Magenta },
            { Text::Color::DarkRed, Text::Color::Cyan },
            { Text::Color::DarkRed, Text::Color::White },
            { Text::Color::DarkGreen, Text::Color::Black },
            { Text::Color::DarkGreen, Text::Color::DarkRed },
            { Text::Color::DarkGreen, Text::Color::DarkGreen },
            { Text::Color::DarkGreen, Text::Color::DarkYellow },
            { Text::Color::DarkGreen, Text::Color::DarkBlue },
            { Text::Color::DarkGreen, Text::Color::DarkMagenta },
            { Text::Color::DarkGreen, Text::Color::DarkCyan },
            { Text::Color::DarkGreen, Text::Color::LightGray },
            { Text::Color::DarkGreen, Text::Color::DarkGray },
            { Text::Color::DarkGreen, Text::Color::Red },
            { Text::Color::DarkGreen, Text::Color::Green },
            { Text::Color::DarkGreen, Text::Color::Yellow },
            { Text::Color::DarkGreen, Text::Color::Blue },
            { Text::Color::DarkGreen, Text::Color::Magenta },
            { Text::Color::DarkGreen, Text::Color::Cyan },
            { Text::Color::DarkGreen, Text::Color::White },
            { Text::Color::DarkYellow, Text::Color::Black },
            { Text::Color::DarkYellow, Text::Color::DarkRed },
            { Text::Color::DarkYellow, Text::Color::DarkGreen },
            { Text::Color::DarkYellow, Text::Color::DarkYellow },
            { Text::Color::DarkYellow, Text::Color::DarkBlue },
            { Text::Color::DarkYellow, Text::Color::DarkMagenta },
            { Text::Color::DarkYellow, Text::Color::DarkCyan },
            { Text::Color::DarkYellow, Text::Color::LightGray },
            { Text::Color::DarkYellow, Text::Color::DarkGray },
            { Text::Color::DarkYellow, Text::Color::Red },
            { Text::Color::DarkYellow, Text::Color::Green },
            { Text::Color::DarkYellow, Text::Color::Yellow },
            { Text::Color::DarkYellow, Text::Color::Blue },
            { Text::Color::DarkYellow, Text::Color::Magenta },
            { Text::Color::DarkYellow, Text::Color::Cyan },
            { Text::Color::DarkYellow, Text::Color::White },
            { Text::Color::DarkBlue, Text::Color::Black },
            { Text::Color::DarkBlue, Text::Color::DarkRed },
            { Text::Color::DarkBlue, Text::Color::DarkGreen },
            { Text::Color::DarkBlue, Text::Color::DarkYellow },
            { Text::Color::DarkBlue, Text::Color::DarkBlue },
            { Text::Color::DarkBlue, Text::Color::DarkMagenta },
            { Text::Color::DarkBlue, Text::Color::DarkCyan },
            { Text::Color::DarkBlue, Text::Color::LightGray },
            { Text::Color::DarkBlue, Text::Color::DarkGray },
            { Text::Color::DarkBlue, Text::Color::Red },
            { Text::Color::DarkBlue, Text::Color::Green },
            { Text::Color::DarkBlue, Text::Color::Yellow },
            { Text::Color::DarkBlue, Text::Color::Blue },
            { Text::Color::DarkBlue, Text::Color::Magenta },
            { Text::Color::DarkBlue, Text::Color::Cyan },
            { Text::Color::DarkBlue, Text::Color::White },
            { Text::Color::DarkMagenta, Text::Color::Black },
            { Text::Color::DarkMagenta, Text::Color::DarkRed },
            { Text::Color::DarkMagenta, Text::Color::DarkGreen },
            { Text::Color::DarkMagenta, Text::Color::DarkYellow },
            { Text::Color::DarkMagenta, Text::Color::DarkBlue },
            { Text::Color::DarkMagenta, Text::Color::DarkMagenta },
            { Text::Color::DarkMagenta, Text::Color::DarkCyan },
            { Text::Color::DarkMagenta, Text::Color::LightGray },
            { Text::Color::DarkMagenta, Text::Color::DarkGray },
            { Text::Color::DarkMagenta, Text::Color::Red },
            { Text::Color::DarkMagenta, Text::Color::Green },
            { Text::Color::DarkMagenta, Text::Color::Yellow },
            { Text::Color::DarkMagenta, Text::Color::Blue },
            { Text::Color::DarkMagenta, Text::Color::Magenta },
            { Text::Color::DarkMagenta, Text::Color::Cyan },
            { Text::Color::DarkMagenta, Text::Color::White },
            { Text::Color::DarkCyan, Text::Color::Black },
            { Text::Color::DarkCyan, Text::Color::DarkRed },
            { Text::Color::DarkCyan, Text::Color::DarkGreen },
            { Text::Color::DarkCyan, Text::Color::DarkYellow },
            { Text::Color::DarkCyan, Text::Color::DarkBlue },
            { Text::Color::DarkCyan, Text::Color::DarkMagenta },
            { Text::Color::DarkCyan, Text::Color::DarkCyan },
            { Text::Color::DarkCyan, Text::Color::LightGray },
            { Text::Color::DarkCyan, Text::Color::DarkGray },
            { Text::Color::DarkCyan, Text::Color::Red },
            { Text::Color::DarkCyan, Text::Color::Green },
            { Text::Color::DarkCyan, Text::Color::Yellow },
            { Text::Color::DarkCyan, Text::Color::Blue },
            { Text::Color::DarkCyan, Text::Color::Magenta },
            { Text::Color::DarkCyan, Text::Color::Cyan },
            { Text::Color::DarkCyan, Text::Color::White },
            { Text::Color::LightGray, Text::Color::Black },
            { Text::Color::LightGray, Text::Color::DarkRed },
            { Text::Color::LightGray, Text::Color::DarkGreen },
            { Text::Color::LightGray, Text::Color::DarkYellow },
            { Text::Color::LightGray, Text::Color::DarkBlue },
            { Text::Color::LightGray, Text::Color::DarkMagenta },
            { Text::Color::LightGray, Text::Color::DarkCyan },
            { Text::Color::LightGray, Text::Color::LightGray },
            { Text::Color::LightGray, Text::Color::DarkGray },
            { Text::Color::LightGray, Text::Color::Red },
            { Text::Color::LightGray, Text::Color::Green },
            { Text::Color::LightGray, Text::Color::Yellow },
            { Text::Color::LightGray, Text::Color::Blue },
            { Text::Color::LightGray, Text::Color::Magenta },
            { Text::Color::LightGray, Text::Color::Cyan },
            { Text::Color::LightGray, Text::Color::White },
            { Text::Color::DarkGray, Text::Color::Black },
            { Text::Color::DarkGray, Text::Color::DarkRed },
            { Text::Color::DarkGray, Text::Color::DarkGreen },
            { Text::Color::DarkGray, Text::Color::DarkYellow },
            { Text::Color::DarkGray, Text::Color::DarkBlue },
            { Text::Color::DarkGray, Text::Color::DarkMagenta },
            { Text::Color::DarkGray, Text::Color::DarkCyan },
            { Text::Color::DarkGray, Text::Color::LightGray },
            { Text::Color::DarkGray, Text::Color::DarkGray },
            { Text::Color::DarkGray, Text::Color::Red },
            { Text::Color::DarkGray, Text::Color::Green },
            { Text::Color::DarkGray, Text::Color::Yellow },
            { Text::Color::DarkGray, Text::Color::Blue },
            { Text::Color::DarkGray, Text::Color::Magenta },
            { Text::Color::DarkGray, Text::Color::Cyan },
            { Text::Color::DarkGray, Text::Color::White },
            { Text::Color::Red, Text::Color::Black },
            { Text::Color::Red, Text::Color::DarkRed },
            { Text::Color::Red, Text::Color::DarkGreen },
            { Text::Color::Red, Text::Color::DarkYellow },
            { Text::Color::Red, Text::Color::DarkBlue },
            { Text::Color::Red, Text::Color::DarkMagenta },
            { Text::Color::Red, Text::Color::DarkCyan },
            { Text::Color::Red, Text::Color::LightGray },
            { Text::Color::Red, Text::Color::DarkGray },
            { Text::Color::Red, Text::Color::Red },
            { Text::Color::Red, Text::Color::Green },
            { Text::Color::Red, Text::Color::Yellow },
            { Text::Color::Red, Text::Color::Blue },
            { Text::Color::Red, Text::Color::Magenta },
            { Text::Color::Red, Text::Color::Cyan },
            { Text::Color::Red, Text::Color::White },
            { Text::Color::Green, Text::Color::Black },
            { Text::Color::Green, Text::Color::DarkRed },
            { Text::Color::Green, Text::Color::DarkGreen },
            { Text::Color::Green, Text::Color::DarkYellow },
            { Text::Color::Green, Text::Color::DarkBlue },
            { Text::Color::Green, Text::Color::DarkMagenta },
            { Text::Color::Green, Text::Color::DarkCyan },
            { Text::Color::Green, Text::Color::LightGray },
            { Text::Color::Green, Text::Color::DarkGray },
            { Text::Color::Green, Text::Color::Red },
            { Text::Color::Green, Text::Color::Green },
            { Text::Color::Green, Text::Color::Yellow },
            { Text::Color::Green, Text::Color::Blue },
            { Text::Color::Green, Text::Color::Magenta },
            { Text::Color::Green, Text::Color::Cyan },
            { Text::Color::Green, Text::Color::White },
            { Text::Color::Yellow, Text::Color::Black },
            { Text::Color::Yellow, Text::Color::DarkRed },
            { Text::Color::Yellow, Text::Color::DarkGreen },
            { Text::Color::Yellow, Text::Color::DarkYellow },
            { Text::Color::Yellow, Text::Color::DarkBlue },
            { Text::Color::Yellow, Text::Color::DarkMagenta },
            { Text::Color::Yellow, Text::Color::DarkCyan },
            { Text::Color::Yellow, Text::Color::LightGray },
            { Text::Color::Yellow, Text::Color::DarkGray },
            { Text::Color::Yellow, Text::Color::Red },
            { Text::Color::Yellow, Text::Color::Green },
            { Text::Color::Yellow, Text::Color::Yellow },
            { Text::Color::Yellow, Text::Color::Blue },
            { Text::Color::Yellow, Text::Color::Magenta },
            { Text::Color::Yellow, Text::Color::Cyan },
            { Text::Color::Yellow, Text::Color::White },
            { Text::Color::Blue, Text::Color::Black },
            { Text::Color::Blue, Text::Color::DarkRed },
            { Text::Color::Blue, Text::Color::DarkGreen },
            { Text::Color::Blue, Text::Color::DarkYellow },
            { Text::Color::Blue, Text::Color::DarkBlue },
            { Text::Color::Blue, Text::Color::DarkMagenta },
            { Text::Color::Blue, Text::Color::DarkCyan },
            { Text::Color::Blue, Text::Color::LightGray },
            { Text::Color::Blue, Text::Color::DarkGray },
            { Text::Color::Blue, Text::Color::Red },
            { Text::Color::Blue, Text::Color::Green },
            { Text::Color::Blue, Text::Color::Yellow },
            { Text::Color::Blue, Text::Color::Blue },
            { Text::Color::Blue, Text::Color::Magenta },
            { Text::Color::Blue, Text::Color::Cyan },
            { Text::Color::Blue, Text::Color::White },
            { Text::Color::Magenta, Text::Color::Black },
            { Text::Color::Magenta, Text::Color::DarkRed },
            { Text::Color::Magenta, Text::Color::DarkGreen },
            { Text::Color::Magenta, Text::Color::DarkYellow },
            { Text::Color::Magenta, Text::Color::DarkBlue },
            { Text::Color::Magenta, Text::Color::DarkMagenta },
            { Text::Color::Magenta, Text::Color::DarkCyan },
            { Text::Color::Magenta, Text::Color::LightGray },
            { Text::Color::Magenta, Text::Color::DarkGray },
            { Text::Color::Magenta, Text::Color::Red },
            { Text::Color::Magenta, Text::Color::Green },
            { Text::Color::Magenta, Text::Color::Yellow },
            { Text::Color::Magenta, Text::Color::Blue },
            { Text::Color::Magenta, Text::Color::Magenta },
            { Text::Color::Magenta, Text::Color::Cyan },
            { Text::Color::Magenta, Text::Color::White },
            { Text::Color::Cyan, Text::Color::Black },
            { Text::Color::Cyan, Text::Color::DarkRed },
            { Text::Color::Cyan, Text::Color::DarkGreen },
            { Text::Color::Cyan, Text::Color::DarkYellow },
            { Text::Color::Cyan, Text::Color::DarkBlue },
            { Text::Color::Cyan, Text::Color::DarkMagenta },
            { Text::Color::Cyan, Text::Color::DarkCyan },
            { Text::Color::Cyan, Text::Color::LightGray },
            { Text::Color::Cyan, Text::Color::DarkGray },
            { Text::Color::Cyan, Text::Color::Red },
            { Text::Color::Cyan, Text::Color::Green },
            { Text::Color::Cyan, Text::Color::Yellow },
            { Text::Color::Cyan, Text::Color::Blue },
            { Text::Color::Cyan, Text::Color::Magenta },
            { Text::Color::Cyan, Text::Color::Cyan },
            { Text::Color::Cyan, Text::Color::White },
            { Text::Color::White, Text::Color::Black },
            { Text::Color::White, Text::Color::DarkRed },
            { Text::Color::White, Text::Color::DarkGreen },
            { Text::Color::White, Text::Color::DarkYellow },
            { Text::Color::White, Text::Color::DarkBlue },
            { Text::Color::White, Text::Color::DarkMagenta },
            { Text::Color::White, Text::Color::DarkCyan },
            { Text::Color::White, Text::Color::LightGray },
            { Text::Color::White, Text::Color::DarkGray },
            { Text::Color::White, Text::Color::Red },
            { Text::Color::White, Text::Color::Green },
            { Text::Color::White, Text::Color::Yellow },
            { Text::Color::White, Text::Color::Blue },
            { Text::Color::White, Text::Color::Magenta },
            { Text::Color::White, Text::Color::Cyan },
            { Text::Color::White, Text::Color::White },
          }
        },
        { WallBasicType::Other,
          {
            { Text::Color::Black, Text::Color::Black },
            { Text::Color::Black, Text::Color::DarkRed },
            { Text::Color::Black, Text::Color::DarkGreen },
            { Text::Color::Black, Text::Color::DarkYellow },
            { Text::Color::Black, Text::Color::DarkBlue },
            { Text::Color::Black, Text::Color::DarkMagenta },
            { Text::Color::Black, Text::Color::DarkCyan },
            { Text::Color::Black, Text::Color::LightGray },
            { Text::Color::Black, Text::Color::DarkGray },
            { Text::Color::Black, Text::Color::Red },
            { Text::Color::Black, Text::Color::Green },
            { Text::Color::Black, Text::Color::Yellow },
            { Text::Color::Black, Text::Color::Blue },
            { Text::Color::Black, Text::Color::Magenta },
            { Text::Color::Black, Text::Color::Cyan },
            { Text::Color::Black, Text::Color::White },
            { Text::Color::DarkRed, Text::Color::Black },
            { Text::Color::DarkRed, Text::Color::DarkRed },
            { Text::Color::DarkRed, Text::Color::DarkGreen },
            { Text::Color::DarkRed, Text::Color::DarkYellow },
            { Text::Color::DarkRed, Text::Color::DarkBlue },
            { Text::Color::DarkRed, Text::Color::DarkMagenta },
            { Text::Color::DarkRed, Text::Color::DarkCyan },
            { Text::Color::DarkRed, Text::Color::LightGray },
            { Text::Color::DarkRed, Text::Color::DarkGray },
            { Text::Color::DarkRed, Text::Color::Red },
            { Text::Color::DarkRed, Text::Color::Green },
            { Text::Color::DarkRed, Text::Color::Yellow },
            { Text::Color::DarkRed, Text::Color::Blue },
            { Text::Color::DarkRed, Text::Color::Magenta },
            { Text::Color::DarkRed, Text::Color::Cyan },
            { Text::Color::DarkRed, Text::Color::White },
            { Text::Color::DarkGreen, Text::Color::Black },
            { Text::Color::DarkGreen, Text::Color::DarkRed },
            { Text::Color::DarkGreen, Text::Color::DarkGreen },
            { Text::Color::DarkGreen, Text::Color::DarkYellow },
            { Text::Color::DarkGreen, Text::Color::DarkBlue },
            { Text::Color::DarkGreen, Text::Color::DarkMagenta },
            { Text::Color::DarkGreen, Text::Color::DarkCyan },
            { Text::Color::DarkGreen, Text::Color::LightGray },
            { Text::Color::DarkGreen, Text::Color::DarkGray },
            { Text::Color::DarkGreen, Text::Color::Red },
            { Text::Color::DarkGreen, Text::Color::Green },
            { Text::Color::DarkGreen, Text::Color::Yellow },
            { Text::Color::DarkGreen, Text::Color::Blue },
            { Text::Color::DarkGreen, Text::Color::Magenta },
            { Text::Color::DarkGreen, Text::Color::Cyan },
            { Text::Color::DarkGreen, Text::Color::White },
            { Text::Color::DarkYellow, Text::Color::Black },
            { Text::Color::DarkYellow, Text::Color::DarkRed },
            { Text::Color::DarkYellow, Text::Color::DarkGreen },
            { Text::Color::DarkYellow, Text::Color::DarkYellow },
            { Text::Color::DarkYellow, Text::Color::DarkBlue },
            { Text::Color::DarkYellow, Text::Color::DarkMagenta },
            { Text::Color::DarkYellow, Text::Color::DarkCyan },
            { Text::Color::DarkYellow, Text::Color::LightGray },
            { Text::Color::DarkYellow, Text::Color::DarkGray },
            { Text::Color::DarkYellow, Text::Color::Red },
            { Text::Color::DarkYellow, Text::Color::Green },
            { Text::Color::DarkYellow, Text::Color::Yellow },
            { Text::Color::DarkYellow, Text::Color::Blue },
            { Text::Color::DarkYellow, Text::Color::Magenta },
            { Text::Color::DarkYellow, Text::Color::Cyan },
            { Text::Color::DarkYellow, Text::Color::White },
            { Text::Color::DarkBlue, Text::Color::Black },
            { Text::Color::DarkBlue, Text::Color::DarkRed },
            { Text::Color::DarkBlue, Text::Color::DarkGreen },
            { Text::Color::DarkBlue, Text::Color::DarkYellow },
            { Text::Color::DarkBlue, Text::Color::DarkBlue },
            { Text::Color::DarkBlue, Text::Color::DarkMagenta },
            { Text::Color::DarkBlue, Text::Color::DarkCyan },
            { Text::Color::DarkBlue, Text::Color::LightGray },
            { Text::Color::DarkBlue, Text::Color::DarkGray },
            { Text::Color::DarkBlue, Text::Color::Red },
            { Text::Color::DarkBlue, Text::Color::Green },
            { Text::Color::DarkBlue, Text::Color::Yellow },
            { Text::Color::DarkBlue, Text::Color::Blue },
            { Text::Color::DarkBlue, Text::Color::Magenta },
            { Text::Color::DarkBlue, Text::Color::Cyan },
            { Text::Color::DarkBlue, Text::Color::White },
            { Text::Color::DarkMagenta, Text::Color::Black },
            { Text::Color::DarkMagenta, Text::Color::DarkRed },
            { Text::Color::DarkMagenta, Text::Color::DarkGreen },
            { Text::Color::DarkMagenta, Text::Color::DarkYellow },
            { Text::Color::DarkMagenta, Text::Color::DarkBlue },
            { Text::Color::DarkMagenta, Text::Color::DarkMagenta },
            { Text::Color::DarkMagenta, Text::Color::DarkCyan },
            { Text::Color::DarkMagenta, Text::Color::LightGray },
            { Text::Color::DarkMagenta, Text::Color::DarkGray },
            { Text::Color::DarkMagenta, Text::Color::Red },
            { Text::Color::DarkMagenta, Text::Color::Green },
            { Text::Color::DarkMagenta, Text::Color::Yellow },
            { Text::Color::DarkMagenta, Text::Color::Blue },
            { Text::Color::DarkMagenta, Text::Color::Magenta },
            { Text::Color::DarkMagenta, Text::Color::Cyan },
            { Text::Color::DarkMagenta, Text::Color::White },
            { Text::Color::DarkCyan, Text::Color::Black },
            { Text::Color::DarkCyan, Text::Color::DarkRed },
            { Text::Color::DarkCyan, Text::Color::DarkGreen },
            { Text::Color::DarkCyan, Text::Color::DarkYellow },
            { Text::Color::DarkCyan, Text::Color::DarkBlue },
            { Text::Color::DarkCyan, Text::Color::DarkMagenta },
            { Text::Color::DarkCyan, Text::Color::DarkCyan },
            { Text::Color::DarkCyan, Text::Color::LightGray },
            { Text::Color::DarkCyan, Text::Color::DarkGray },
            { Text::Color::DarkCyan, Text::Color::Red },
            { Text::Color::DarkCyan, Text::Color::Green },
            { Text::Color::DarkCyan, Text::Color::Yellow },
            { Text::Color::DarkCyan, Text::Color::Blue },
            { Text::Color::DarkCyan, Text::Color::Magenta },
            { Text::Color::DarkCyan, Text::Color::Cyan },
            { Text::Color::DarkCyan, Text::Color::White },
            { Text::Color::LightGray, Text::Color::Black },
            { Text::Color::LightGray, Text::Color::DarkRed },
            { Text::Color::LightGray, Text::Color::DarkGreen },
            { Text::Color::LightGray, Text::Color::DarkYellow },
            { Text::Color::LightGray, Text::Color::DarkBlue },
            { Text::Color::LightGray, Text::Color::DarkMagenta },
            { Text::Color::LightGray, Text::Color::DarkCyan },
            { Text::Color::LightGray, Text::Color::LightGray },
            { Text::Color::LightGray, Text::Color::DarkGray },
            { Text::Color::LightGray, Text::Color::Red },
            { Text::Color::LightGray, Text::Color::Green },
            { Text::Color::LightGray, Text::Color::Yellow },
            { Text::Color::LightGray, Text::Color::Blue },
            { Text::Color::LightGray, Text::Color::Magenta },
            { Text::Color::LightGray, Text::Color::Cyan },
            { Text::Color::LightGray, Text::Color::White },
            { Text::Color::DarkGray, Text::Color::Black },
            { Text::Color::DarkGray, Text::Color::DarkRed },
            { Text::Color::DarkGray, Text::Color::DarkGreen },
            { Text::Color::DarkGray, Text::Color::DarkYellow },
            { Text::Color::DarkGray, Text::Color::DarkBlue },
            { Text::Color::DarkGray, Text::Color::DarkMagenta },
            { Text::Color::DarkGray, Text::Color::DarkCyan },
            { Text::Color::DarkGray, Text::Color::LightGray },
            { Text::Color::DarkGray, Text::Color::DarkGray },
            { Text::Color::DarkGray, Text::Color::Red },
            { Text::Color::DarkGray, Text::Color::Green },
            { Text::Color::DarkGray, Text::Color::Yellow },
            { Text::Color::DarkGray, Text::Color::Blue },
            { Text::Color::DarkGray, Text::Color::Magenta },
            { Text::Color::DarkGray, Text::Color::Cyan },
            { Text::Color::DarkGray, Text::Color::White },
            { Text::Color::Red, Text::Color::Black },
            { Text::Color::Red, Text::Color::DarkRed },
            { Text::Color::Red, Text::Color::DarkGreen },
            { Text::Color::Red, Text::Color::DarkYellow },
            { Text::Color::Red, Text::Color::DarkBlue },
            { Text::Color::Red, Text::Color::DarkMagenta },
            { Text::Color::Red, Text::Color::DarkCyan },
            { Text::Color::Red, Text::Color::LightGray },
            { Text::Color::Red, Text::Color::DarkGray },
            { Text::Color::Red, Text::Color::Red },
            { Text::Color::Red, Text::Color::Green },
            { Text::Color::Red, Text::Color::Yellow },
            { Text::Color::Red, Text::Color::Blue },
            { Text::Color::Red, Text::Color::Magenta },
            { Text::Color::Red, Text::Color::Cyan },
            { Text::Color::Red, Text::Color::White },
            { Text::Color::Green, Text::Color::Black },
            { Text::Color::Green, Text::Color::DarkRed },
            { Text::Color::Green, Text::Color::DarkGreen },
            { Text::Color::Green, Text::Color::DarkYellow },
            { Text::Color::Green, Text::Color::DarkBlue },
            { Text::Color::Green, Text::Color::DarkMagenta },
            { Text::Color::Green, Text::Color::DarkCyan },
            { Text::Color::Green, Text::Color::LightGray },
            { Text::Color::Green, Text::Color::DarkGray },
            { Text::Color::Green, Text::Color::Red },
            { Text::Color::Green, Text::Color::Green },
            { Text::Color::Green, Text::Color::Yellow },
            { Text::Color::Green, Text::Color::Blue },
            { Text::Color::Green, Text::Color::Magenta },
            { Text::Color::Green, Text::Color::Cyan },
            { Text::Color::Green, Text::Color::White },
            { Text::Color::Yellow, Text::Color::Black },
            { Text::Color::Yellow, Text::Color::DarkRed },
            { Text::Color::Yellow, Text::Color::DarkGreen },
            { Text::Color::Yellow, Text::Color::DarkYellow },
            { Text::Color::Yellow, Text::Color::DarkBlue },
            { Text::Color::Yellow, Text::Color::DarkMagenta },
            { Text::Color::Yellow, Text::Color::DarkCyan },
            { Text::Color::Yellow, Text::Color::LightGray },
            { Text::Color::Yellow, Text::Color::DarkGray },
            { Text::Color::Yellow, Text::Color::Red },
            { Text::Color::Yellow, Text::Color::Green },
            { Text::Color::Yellow, Text::Color::Yellow },
            { Text::Color::Yellow, Text::Color::Blue },
            { Text::Color::Yellow, Text::Color::Magenta },
            { Text::Color::Yellow, Text::Color::Cyan },
            { Text::Color::Yellow, Text::Color::White },
            { Text::Color::Blue, Text::Color::Black },
            { Text::Color::Blue, Text::Color::DarkRed },
            { Text::Color::Blue, Text::Color::DarkGreen },
            { Text::Color::Blue, Text::Color::DarkYellow },
            { Text::Color::Blue, Text::Color::DarkBlue },
            { Text::Color::Blue, Text::Color::DarkMagenta },
            { Text::Color::Blue, Text::Color::DarkCyan },
            { Text::Color::Blue, Text::Color::LightGray },
            { Text::Color::Blue, Text::Color::DarkGray },
            { Text::Color::Blue, Text::Color::Red },
            { Text::Color::Blue, Text::Color::Green },
            { Text::Color::Blue, Text::Color::Yellow },
            { Text::Color::Blue, Text::Color::Blue },
            { Text::Color::Blue, Text::Color::Magenta },
            { Text::Color::Blue, Text::Color::Cyan },
            { Text::Color::Blue, Text::Color::White },
            { Text::Color::Magenta, Text::Color::Black },
            { Text::Color::Magenta, Text::Color::DarkRed },
            { Text::Color::Magenta, Text::Color::DarkGreen },
            { Text::Color::Magenta, Text::Color::DarkYellow },
            { Text::Color::Magenta, Text::Color::DarkBlue },
            { Text::Color::Magenta, Text::Color::DarkMagenta },
            { Text::Color::Magenta, Text::Color::DarkCyan },
            { Text::Color::Magenta, Text::Color::LightGray },
            { Text::Color::Magenta, Text::Color::DarkGray },
            { Text::Color::Magenta, Text::Color::Red },
            { Text::Color::Magenta, Text::Color::Green },
            { Text::Color::Magenta, Text::Color::Yellow },
            { Text::Color::Magenta, Text::Color::Blue },
            { Text::Color::Magenta, Text::Color::Magenta },
            { Text::Color::Magenta, Text::Color::Cyan },
            { Text::Color::Magenta, Text::Color::White },
            { Text::Color::Cyan, Text::Color::Black },
            { Text::Color::Cyan, Text::Color::DarkRed },
            { Text::Color::Cyan, Text::Color::DarkGreen },
            { Text::Color::Cyan, Text::Color::DarkYellow },
            { Text::Color::Cyan, Text::Color::DarkBlue },
            { Text::Color::Cyan, Text::Color::DarkMagenta },
            { Text::Color::Cyan, Text::Color::DarkCyan },
            { Text::Color::Cyan, Text::Color::LightGray },
            { Text::Color::Cyan, Text::Color::DarkGray },
            { Text::Color::Cyan, Text::Color::Red },
            { Text::Color::Cyan, Text::Color::Green },
            { Text::Color::Cyan, Text::Color::Yellow },
            { Text::Color::Cyan, Text::Color::Blue },
            { Text::Color::Cyan, Text::Color::Magenta },
            { Text::Color::Cyan, Text::Color::Cyan },
            { Text::Color::Cyan, Text::Color::White },
            { Text::Color::White, Text::Color::Black },
            { Text::Color::White, Text::Color::DarkRed },
            { Text::Color::White, Text::Color::DarkGreen },
            { Text::Color::White, Text::Color::DarkYellow },
            { Text::Color::White, Text::Color::DarkBlue },
            { Text::Color::White, Text::Color::DarkMagenta },
            { Text::Color::White, Text::Color::DarkCyan },
            { Text::Color::White, Text::Color::LightGray },
            { Text::Color::White, Text::Color::DarkGray },
            { Text::Color::White, Text::Color::Red },
            { Text::Color::White, Text::Color::Green },
            { Text::Color::White, Text::Color::Yellow },
            { Text::Color::White, Text::Color::Blue },
            { Text::Color::White, Text::Color::Magenta },
            { Text::Color::White, Text::Color::Cyan },
            { Text::Color::White, Text::Color::White },
          }
        },
      };
      
    public:
      WallType wall_type = WallType::Hash;
      Style wall_style { Text::Color::DarkGray, Text::Color::LightGray };
      FloorType floor_type = FloorType::None;
      bool is_underground = true;
      
      void init_rand()
      {
        //wall_type = rnd::rand_enum<WallType>();
        wall_type = WallType::Masonry;
        WallBasicType wall_basic_type = WallBasicType::Other;
        switch (wall_type)
        {
          case WallType::Masonry:
          case WallType::Masonry2:
          case WallType::Masonry3:
          case WallType::Masonry4:
            wall_basic_type = WallBasicType::Masonry;
          case WallType::Temple:
            wall_basic_type = WallBasicType::Temple;
          case WallType::Line:
          case WallType::Hash:
          default:
            wall_basic_type = WallBasicType::Other;
            break;
        }
        wall_style = styles::get_random_style(wall_palette[wall_basic_type]);
        floor_type = rnd::rand_enum<FloorType>();
        is_underground = rnd::rand_bool();
      }
      
      char get_fill_char() const
      {
        switch (floor_type)
        {
          case FloorType::Sand:
            return ':';
          case FloorType::Grass:
            return '|';
          case FloorType::Stone:
            return 'H';
          case FloorType::Stone2:
            return '8';
          case FloorType::Water:
            return '~';
          case FloorType::Wood:
            return 'W';
          case FloorType::None:
          default:
            return ' ';
            break;
        }
      }
      
      char get_shadow_char() const
      {
        return get_fill_char();
      }
      
      Style get_fill_style() const
      {
        Style style;
        switch (floor_type)
        {
          case FloorType::Sand:
            style = { Text::Color::DarkYellow, Text::Color::Yellow };
            break;
          case FloorType::Grass:
            style = { Text::Color::DarkGreen, Text::Color::Green };
            break;
          case FloorType::Stone:
          case FloorType::Stone2:
            style = { Text::Color::DarkGray, Text::Color::LightGray };
            break;
          case FloorType::Water:
            style = { Text::Color::DarkBlue, Text::Color::Blue };
            break;
          case FloorType::Wood:
            style = { Text::Color::DarkRed, Text::Color::Yellow };
            break;
          case FloorType::None:
          default:
            style = { Text::Color::Black, Text::Color::LightGray };
            break;
        }
        if (is_underground)
          std::swap(style.fg_color, style.bg_color);
        return style;
      }
      
      Style get_shadow_style() const
      {
        switch (floor_type)
        {
          case FloorType::Sand:
            return { Text::Color::Yellow, Text::Color::DarkYellow };
          case FloorType::Grass:
            return { Text::Color::Green, Text::Color::DarkGreen };
          case FloorType::Stone:
          case FloorType::Stone2:
            return { Text::Color::LightGray, Text::Color::DarkGray };
          case FloorType::Water:
            return { Text::Color::Blue, Text::Color::DarkBlue };
          case FloorType::Wood:
            return { Text::Color::Red, Text::Color::DarkYellow };
          case FloorType::None:
          default:
            return { Text::Color::Black, Text::Color::DarkGray };
            break;
        }
      }
    };
    
    std::map<BSPNode*, RoomStyle> m_room_styles;
    
  public:
    DungGine() = default;
    
    void load_dungeon(BSPTree* bsp_tree)
    {
      m_bsp_tree = bsp_tree;
      m_leaves = m_bsp_tree->fetch_leaves();
    }
    
    void style_dungeon()
    {
      for (auto* leaf : m_leaves)
      {
        RoomStyle room_style;
        room_style.init_rand();
        m_room_styles[leaf] = room_style;
      }
    }
    
    template<int NR, int NC>
    void draw(SpriteHandler<NR, NC>& sh, int r0 = 0, int c0 = 0) const
    {
      auto shadow_type = rnd::rand_enum<ShadowType>(); // Random for now.
      for (const auto& room_pair : m_room_styles)
      {
        const auto& bb = room_pair.first->bb_leaf_room;
        const auto& room_style = room_pair.second;
        drawing::draw_box(sh,
                          r0 + bb.r, c0 + bb.c, bb.r_len, bb.c_len,
                          room_style.wall_type,
                          room_style.wall_style,
                          room_style.get_fill_style(),
                          room_style.get_fill_char(),
                          room_style.is_underground ? ShadowType::None : shadow_type,
                          room_style.get_shadow_style(),
                          room_style.get_fill_char());
      }
    }
    
  };
  
}
