//
//  DungGineStyles.h
//  DungGine
//
//  Created by Rasmus Anthin on 2024-06-14.
//

#pragma once
#include <Termin8or/screen/Styles.h>
#include <Core/StlUtils.h>


namespace dung
{

  using Color16 = t8::Color16;
  using Color = t8::Color;
  
  enum class WallBasicType { MasonryLight, MasonryDark, TempleLight, TempleDark, OtherLight, OtherDark };
  
  inline std::map<WallBasicType, std::vector<t8::Style>> wall_palette
  {
    { WallBasicType::MasonryLight,
      {
        { Color16::Black, Color16::LightGray },
        { Color16::Black, Color16::Red },
        { Color16::Black, Color16::Green },
        { Color16::Black, Color16::Yellow },
        { Color16::Black, Color16::Blue },
        { Color16::Black, Color16::Magenta },
        { Color16::Black, Color16::Cyan },
        { Color16::Black, Color16::White },
        { Color16::DarkRed, Color16::LightGray },
        { Color16::DarkRed, Color16::Red },
        { Color16::DarkRed, Color16::Green },
        { Color16::DarkRed, Color16::Yellow },
        { Color16::DarkRed, Color16::Blue },
        { Color16::DarkRed, Color16::Magenta },
        { Color16::DarkRed, Color16::Cyan },
        { Color16::DarkRed, Color16::White },
        { Color16::DarkGreen, Color16::LightGray },
        { Color16::DarkGreen, Color16::Red },
        { Color16::DarkGreen, Color16::Green },
        { Color16::DarkGreen, Color16::Yellow },
        { Color16::DarkGreen, Color16::Blue },
        { Color16::DarkGreen, Color16::Magenta },
        { Color16::DarkGreen, Color16::Cyan },
        { Color16::DarkGreen, Color16::White },
        { Color16::DarkYellow, Color16::LightGray },
        { Color16::DarkYellow, Color16::Red },
        { Color16::DarkYellow, Color16::Green },
        { Color16::DarkYellow, Color16::Yellow },
        { Color16::DarkYellow, Color16::Blue },
        { Color16::DarkYellow, Color16::Magenta },
        { Color16::DarkYellow, Color16::Cyan },
        { Color16::DarkYellow, Color16::White },
        { Color16::DarkBlue, Color16::LightGray },
        { Color16::DarkBlue, Color16::Red },
        { Color16::DarkBlue, Color16::Green },
        { Color16::DarkBlue, Color16::Yellow },
        { Color16::DarkBlue, Color16::Blue },
        { Color16::DarkBlue, Color16::Magenta },
        { Color16::DarkBlue, Color16::Cyan },
        { Color16::DarkBlue, Color16::White },
        { Color16::DarkMagenta, Color16::LightGray },
        { Color16::DarkMagenta, Color16::Red },
        { Color16::DarkMagenta, Color16::Green },
        { Color16::DarkMagenta, Color16::Yellow },
        { Color16::DarkMagenta, Color16::Blue },
        //{ Color16::DarkMagenta, Color16::Magenta },
        { Color16::DarkMagenta, Color16::Cyan },
        { Color16::DarkMagenta, Color16::White },
        { Color16::DarkCyan, Color16::LightGray },
        { Color16::DarkCyan, Color16::Red },
        { Color16::DarkCyan, Color16::Green },
        { Color16::DarkCyan, Color16::Yellow },
        { Color16::DarkCyan, Color16::Blue },
        { Color16::DarkCyan, Color16::Magenta },
        { Color16::DarkCyan, Color16::Cyan },
        { Color16::DarkCyan, Color16::White },
        { Color16::LightGray, Color16::LightGray },
        { Color16::LightGray, Color16::Red },
        { Color16::LightGray, Color16::Green },
        { Color16::LightGray, Color16::Yellow },
        { Color16::LightGray, Color16::Blue },
        //{ Color16::LightGray, Color16::Magenta },
        { Color16::LightGray, Color16::Cyan },
        { Color16::LightGray, Color16::White },
        { Color16::DarkGray, Color16::LightGray },
        { Color16::DarkGray, Color16::Red },
        { Color16::DarkGray, Color16::Green },
        { Color16::DarkGray, Color16::Yellow },
        { Color16::DarkGray, Color16::Blue },
        { Color16::DarkGray, Color16::Magenta },
        { Color16::DarkGray, Color16::Cyan },
        { Color16::DarkGray, Color16::White },
        { Color16::Red, Color16::LightGray },
        { Color16::Red, Color16::Red },
        { Color16::Red, Color16::Green },
        { Color16::Red, Color16::Yellow },
        { Color16::Red, Color16::Blue },
        { Color16::Red, Color16::Magenta },
        { Color16::Red, Color16::Cyan },
        { Color16::Red, Color16::White },
        { Color16::Green, Color16::LightGray },
        { Color16::Green, Color16::Red },
        { Color16::Green, Color16::Green },
        { Color16::Green, Color16::Yellow },
        { Color16::Green, Color16::Blue },
        { Color16::Green, Color16::Magenta },
        { Color16::Green, Color16::Cyan },
        { Color16::Green, Color16::White },
        { Color16::Yellow, Color16::LightGray },
        { Color16::Yellow, Color16::Red },
        { Color16::Yellow, Color16::Green },
        { Color16::Yellow, Color16::Yellow },
        { Color16::Yellow, Color16::Blue },
        { Color16::Yellow, Color16::Magenta },
        { Color16::Yellow, Color16::Cyan },
        { Color16::Yellow, Color16::White },
        { Color16::Blue, Color16::LightGray },
        { Color16::Blue, Color16::Red },
        { Color16::Blue, Color16::Green },
        { Color16::Blue, Color16::Yellow },
        { Color16::Blue, Color16::Blue },
        { Color16::Blue, Color16::Magenta },
        { Color16::Blue, Color16::Cyan },
        { Color16::Blue, Color16::White },
        { Color16::Magenta, Color16::LightGray },
        { Color16::Magenta, Color16::Red },
        { Color16::Magenta, Color16::Green },
        { Color16::Magenta, Color16::Yellow },
        { Color16::Magenta, Color16::Blue },
        { Color16::Magenta, Color16::Magenta },
        { Color16::Magenta, Color16::Cyan },
        { Color16::Magenta, Color16::White },
        { Color16::Cyan, Color16::LightGray },
        //{ Color16::Cyan, Color16::Red },
        { Color16::Cyan, Color16::Green },
        { Color16::Cyan, Color16::Yellow },
        { Color16::Cyan, Color16::Blue },
        //{ Color16::Cyan, Color16::Magenta },
        { Color16::Cyan, Color16::Cyan },
        { Color16::Cyan, Color16::White },
        { Color16::White, Color16::LightGray },
        { Color16::White, Color16::Red },
        { Color16::White, Color16::Green },
        { Color16::White, Color16::Yellow },
        { Color16::White, Color16::Blue },
        { Color16::White, Color16::Magenta },
        { Color16::White, Color16::Cyan },
        { Color16::White, Color16::White },
      }
    },
    {
      WallBasicType::MasonryDark,
      {
        { Color16::Black, Color16::Black },
        { Color16::Black, Color16::DarkRed },
        { Color16::Black, Color16::DarkGreen },
        { Color16::Black, Color16::DarkYellow },
        { Color16::Black, Color16::DarkBlue },
        { Color16::Black, Color16::DarkMagenta },
        { Color16::Black, Color16::DarkCyan },
        { Color16::Black, Color16::DarkGray },
        { Color16::DarkRed, Color16::Black },
        { Color16::DarkRed, Color16::DarkRed },
        { Color16::DarkRed, Color16::DarkGreen },
        { Color16::DarkRed, Color16::DarkYellow },
        //{ Color16::DarkRed, Color16::DarkBlue },
        { Color16::DarkRed, Color16::DarkMagenta },
        { Color16::DarkRed, Color16::DarkCyan },
        { Color16::DarkRed, Color16::DarkGray },
        { Color16::DarkGreen, Color16::Black },
        { Color16::DarkGreen, Color16::DarkRed },
        { Color16::DarkGreen, Color16::DarkGreen },
        { Color16::DarkGreen, Color16::DarkYellow },
        { Color16::DarkGreen, Color16::DarkBlue },
        { Color16::DarkGreen, Color16::DarkMagenta },
        { Color16::DarkGreen, Color16::DarkCyan },
        { Color16::DarkGreen, Color16::DarkGray },
        { Color16::DarkYellow, Color16::Black },
        { Color16::DarkYellow, Color16::DarkRed },
        { Color16::DarkYellow, Color16::DarkGreen },
        { Color16::DarkYellow, Color16::DarkYellow },
        { Color16::DarkYellow, Color16::DarkBlue },
        { Color16::DarkYellow, Color16::DarkMagenta },
        { Color16::DarkYellow, Color16::DarkCyan },
        { Color16::DarkYellow, Color16::DarkGray },
        { Color16::DarkBlue, Color16::Black },
        { Color16::DarkBlue, Color16::DarkRed },
        { Color16::DarkBlue, Color16::DarkGreen },
        { Color16::DarkBlue, Color16::DarkYellow },
        { Color16::DarkBlue, Color16::DarkBlue },
        { Color16::DarkBlue, Color16::DarkMagenta },
        { Color16::DarkBlue, Color16::DarkCyan },
        { Color16::DarkBlue, Color16::DarkGray },
        { Color16::DarkMagenta, Color16::Black },
        { Color16::DarkMagenta, Color16::DarkRed },
        { Color16::DarkMagenta, Color16::DarkGreen },
        { Color16::DarkMagenta, Color16::DarkYellow },
        { Color16::DarkMagenta, Color16::DarkBlue },
        //{ Color16::DarkMagenta, Color16::DarkMagenta },
        { Color16::DarkMagenta, Color16::DarkCyan },
        { Color16::DarkMagenta, Color16::DarkGray },
        { Color16::DarkCyan, Color16::Black },
        { Color16::DarkCyan, Color16::DarkRed },
        { Color16::DarkCyan, Color16::DarkGreen },
        { Color16::DarkCyan, Color16::DarkYellow },
        { Color16::DarkCyan, Color16::DarkBlue },
        { Color16::DarkCyan, Color16::DarkMagenta },
        { Color16::DarkCyan, Color16::DarkCyan },
        { Color16::DarkCyan, Color16::DarkGray },
        { Color16::LightGray, Color16::Black },
        { Color16::LightGray, Color16::DarkRed },
        { Color16::LightGray, Color16::DarkGreen },
        { Color16::LightGray, Color16::DarkYellow },
        { Color16::LightGray, Color16::DarkBlue },
        { Color16::LightGray, Color16::DarkMagenta },
        { Color16::LightGray, Color16::DarkCyan },
        { Color16::LightGray, Color16::DarkGray },
        { Color16::DarkGray, Color16::Black },
        { Color16::DarkGray, Color16::DarkRed },
        { Color16::DarkGray, Color16::DarkGreen },
        { Color16::DarkGray, Color16::DarkYellow },
        { Color16::DarkGray, Color16::DarkBlue },
        { Color16::DarkGray, Color16::DarkMagenta },
        { Color16::DarkGray, Color16::DarkCyan },
        { Color16::DarkGray, Color16::DarkGray },
        { Color16::Red, Color16::Black },
        { Color16::Red, Color16::DarkRed },
        { Color16::Red, Color16::DarkGreen },
        { Color16::Red, Color16::DarkYellow },
        //{ Color16::Red, Color16::DarkBlue },
        { Color16::Red, Color16::DarkMagenta },
        { Color16::Red, Color16::DarkCyan },
        { Color16::Red, Color16::DarkGray },
        { Color16::Green, Color16::Black },
        { Color16::Green, Color16::DarkRed },
        //{ Color16::Green, Color16::DarkGreen },
        { Color16::Green, Color16::DarkYellow },
        { Color16::Green, Color16::DarkBlue },
        { Color16::Green, Color16::DarkMagenta },
        { Color16::Green, Color16::DarkCyan },
        { Color16::Green, Color16::DarkGray },
        { Color16::Yellow, Color16::Black },
        { Color16::Yellow, Color16::DarkRed },
        { Color16::Yellow, Color16::DarkGreen },
        { Color16::Yellow, Color16::DarkYellow },
        { Color16::Yellow, Color16::DarkBlue },
        { Color16::Yellow, Color16::DarkMagenta },
        { Color16::Yellow, Color16::DarkCyan },
        { Color16::Yellow, Color16::DarkGray },
        { Color16::Blue, Color16::Black },
        { Color16::Blue, Color16::DarkRed },
        { Color16::Blue, Color16::DarkGreen },
        { Color16::Blue, Color16::DarkYellow },
        { Color16::Blue, Color16::DarkBlue },
        { Color16::Blue, Color16::DarkMagenta },
        { Color16::Blue, Color16::DarkCyan },
        { Color16::Blue, Color16::DarkGray },
        { Color16::Magenta, Color16::Black },
        { Color16::Magenta, Color16::DarkRed },
        { Color16::Magenta, Color16::DarkGreen },
        { Color16::Magenta, Color16::DarkYellow },
        { Color16::Magenta, Color16::DarkBlue },
        { Color16::Magenta, Color16::DarkMagenta },
        { Color16::Magenta, Color16::DarkCyan },
        { Color16::Magenta, Color16::DarkGray },
        { Color16::Cyan, Color16::Black },
        { Color16::Cyan, Color16::DarkRed },
        { Color16::Cyan, Color16::DarkGreen },
        { Color16::Cyan, Color16::DarkYellow },
        { Color16::Cyan, Color16::DarkBlue },
        { Color16::Cyan, Color16::DarkMagenta },
        { Color16::Cyan, Color16::DarkCyan },
        { Color16::Cyan, Color16::DarkGray },
        { Color16::White, Color16::Black },
        { Color16::White, Color16::DarkRed },
        { Color16::White, Color16::DarkGreen },
        { Color16::White, Color16::DarkYellow },
        { Color16::White, Color16::DarkBlue },
        { Color16::White, Color16::DarkMagenta },
        { Color16::White, Color16::DarkCyan },
        { Color16::White, Color16::DarkGray },
      }
    },
    { WallBasicType::TempleLight,
      {
        { Color16::Black, Color16::LightGray },
        { Color16::Black, Color16::Red },
        { Color16::Black, Color16::Green },
        { Color16::Black, Color16::Yellow },
        { Color16::Black, Color16::Blue },
        { Color16::Black, Color16::Magenta },
        { Color16::Black, Color16::Cyan },
        { Color16::Black, Color16::White },
        { Color16::DarkRed, Color16::LightGray },
        { Color16::DarkRed, Color16::Red },
        { Color16::DarkRed, Color16::Green },
        { Color16::DarkRed, Color16::Yellow },
        { Color16::DarkRed, Color16::Blue },
        { Color16::DarkRed, Color16::Magenta },
        { Color16::DarkRed, Color16::Cyan },
        { Color16::DarkRed, Color16::White },
        { Color16::DarkGreen, Color16::LightGray },
        { Color16::DarkGreen, Color16::Red },
        { Color16::DarkGreen, Color16::Green },
        { Color16::DarkGreen, Color16::Yellow },
        { Color16::DarkGreen, Color16::Blue },
        { Color16::DarkGreen, Color16::Magenta },
        { Color16::DarkGreen, Color16::Cyan },
        { Color16::DarkGreen, Color16::White },
        { Color16::DarkYellow, Color16::LightGray },
        { Color16::DarkYellow, Color16::Red },
        { Color16::DarkYellow, Color16::Green },
        { Color16::DarkYellow, Color16::Yellow },
        { Color16::DarkYellow, Color16::Blue },
        { Color16::DarkYellow, Color16::Magenta },
        { Color16::DarkYellow, Color16::Cyan },
        { Color16::DarkYellow, Color16::White },
        { Color16::DarkBlue, Color16::LightGray },
        { Color16::DarkBlue, Color16::Red },
        { Color16::DarkBlue, Color16::Green },
        { Color16::DarkBlue, Color16::Yellow },
        { Color16::DarkBlue, Color16::Blue },
        { Color16::DarkBlue, Color16::Magenta },
        { Color16::DarkBlue, Color16::Cyan },
        { Color16::DarkBlue, Color16::White },
        { Color16::DarkMagenta, Color16::LightGray },
        { Color16::DarkMagenta, Color16::Red },
        { Color16::DarkMagenta, Color16::Green },
        { Color16::DarkMagenta, Color16::Yellow },
        { Color16::DarkMagenta, Color16::Blue },
        { Color16::DarkMagenta, Color16::Magenta },
        { Color16::DarkMagenta, Color16::Cyan },
        { Color16::DarkMagenta, Color16::White },
        { Color16::DarkCyan, Color16::LightGray },
        { Color16::DarkCyan, Color16::Red },
        { Color16::DarkCyan, Color16::Green },
        { Color16::DarkCyan, Color16::Yellow },
        { Color16::DarkCyan, Color16::Blue },
        { Color16::DarkCyan, Color16::Magenta },
        { Color16::DarkCyan, Color16::Cyan },
        { Color16::DarkCyan, Color16::White },
        { Color16::LightGray, Color16::LightGray },
        { Color16::LightGray, Color16::Red },
        { Color16::LightGray, Color16::Green },
        { Color16::LightGray, Color16::Yellow },
        { Color16::LightGray, Color16::Blue },
        { Color16::LightGray, Color16::Magenta },
        { Color16::LightGray, Color16::Cyan },
        { Color16::LightGray, Color16::White },
        { Color16::DarkGray, Color16::LightGray },
        { Color16::DarkGray, Color16::Red },
        { Color16::DarkGray, Color16::Green },
        { Color16::DarkGray, Color16::Yellow },
        { Color16::DarkGray, Color16::Blue },
        { Color16::DarkGray, Color16::Magenta },
        { Color16::DarkGray, Color16::Cyan },
        { Color16::DarkGray, Color16::White },
        { Color16::Red, Color16::LightGray },
        { Color16::Red, Color16::Red },
        { Color16::Red, Color16::Green },
        { Color16::Red, Color16::Yellow },
        { Color16::Red, Color16::Blue },
        { Color16::Red, Color16::Magenta },
        { Color16::Red, Color16::Cyan },
        { Color16::Red, Color16::White },
        { Color16::Green, Color16::LightGray },
        { Color16::Green, Color16::Red },
        { Color16::Green, Color16::Green },
        { Color16::Green, Color16::Yellow },
        { Color16::Green, Color16::Blue },
        { Color16::Green, Color16::Magenta },
        { Color16::Green, Color16::Cyan },
        { Color16::Green, Color16::White },
        { Color16::Yellow, Color16::LightGray },
        { Color16::Yellow, Color16::Red },
        { Color16::Yellow, Color16::Green },
        { Color16::Yellow, Color16::Yellow },
        { Color16::Yellow, Color16::Blue },
        { Color16::Yellow, Color16::Magenta },
        { Color16::Yellow, Color16::Cyan },
        { Color16::Yellow, Color16::White },
        { Color16::Blue, Color16::LightGray },
        { Color16::Blue, Color16::Red },
        { Color16::Blue, Color16::Green },
        { Color16::Blue, Color16::Yellow },
        { Color16::Blue, Color16::Blue },
        { Color16::Blue, Color16::Magenta },
        { Color16::Blue, Color16::Cyan },
        { Color16::Blue, Color16::White },
        { Color16::Magenta, Color16::LightGray },
        { Color16::Magenta, Color16::Red },
        { Color16::Magenta, Color16::Green },
        { Color16::Magenta, Color16::Yellow },
        { Color16::Magenta, Color16::Blue },
        { Color16::Magenta, Color16::Magenta },
        { Color16::Magenta, Color16::Cyan },
        { Color16::Magenta, Color16::White },
        { Color16::Cyan, Color16::LightGray },
        { Color16::Cyan, Color16::Red },
        { Color16::Cyan, Color16::Green },
        { Color16::Cyan, Color16::Yellow },
        { Color16::Cyan, Color16::Blue },
        { Color16::Cyan, Color16::Magenta },
        { Color16::Cyan, Color16::Cyan },
        { Color16::Cyan, Color16::White },
        { Color16::White, Color16::LightGray },
        { Color16::White, Color16::Red },
        { Color16::White, Color16::Green },
        { Color16::White, Color16::Yellow },
        { Color16::White, Color16::Blue },
        { Color16::White, Color16::Magenta },
        { Color16::White, Color16::Cyan },
        { Color16::White, Color16::White },
      }
    },
    { WallBasicType::TempleDark,
      {
        { Color16::Black, Color16::Black },
        { Color16::Black, Color16::DarkRed },
        { Color16::Black, Color16::DarkGreen },
        { Color16::Black, Color16::DarkYellow },
        { Color16::Black, Color16::DarkBlue },
        { Color16::Black, Color16::DarkMagenta },
        { Color16::Black, Color16::DarkCyan },
        { Color16::Black, Color16::DarkGray },
        { Color16::DarkRed, Color16::Black },
        { Color16::DarkRed, Color16::DarkRed },
        { Color16::DarkRed, Color16::DarkGreen },
        { Color16::DarkRed, Color16::DarkYellow },
        { Color16::DarkRed, Color16::DarkBlue },
        { Color16::DarkRed, Color16::DarkMagenta },
        { Color16::DarkRed, Color16::DarkCyan },
        { Color16::DarkRed, Color16::DarkGray },
        { Color16::DarkGreen, Color16::Black },
        { Color16::DarkGreen, Color16::DarkRed },
        { Color16::DarkGreen, Color16::DarkGreen },
        { Color16::DarkGreen, Color16::DarkYellow },
        { Color16::DarkGreen, Color16::DarkBlue },
        { Color16::DarkGreen, Color16::DarkMagenta },
        { Color16::DarkGreen, Color16::DarkCyan },
        { Color16::DarkGreen, Color16::DarkGray },
        { Color16::DarkYellow, Color16::Black },
        { Color16::DarkYellow, Color16::DarkRed },
        { Color16::DarkYellow, Color16::DarkGreen },
        { Color16::DarkYellow, Color16::DarkYellow },
        { Color16::DarkYellow, Color16::DarkBlue },
        { Color16::DarkYellow, Color16::DarkMagenta },
        { Color16::DarkYellow, Color16::DarkCyan },
        { Color16::DarkYellow, Color16::DarkGray },
        { Color16::DarkBlue, Color16::Black },
        { Color16::DarkBlue, Color16::DarkRed },
        { Color16::DarkBlue, Color16::DarkGreen },
        { Color16::DarkBlue, Color16::DarkYellow },
        { Color16::DarkBlue, Color16::DarkBlue },
        { Color16::DarkBlue, Color16::DarkMagenta },
        { Color16::DarkBlue, Color16::DarkCyan },
        { Color16::DarkBlue, Color16::DarkGray },
        { Color16::DarkMagenta, Color16::Black },
        { Color16::DarkMagenta, Color16::DarkRed },
        { Color16::DarkMagenta, Color16::DarkGreen },
        { Color16::DarkMagenta, Color16::DarkYellow },
        { Color16::DarkMagenta, Color16::DarkBlue },
        { Color16::DarkMagenta, Color16::DarkMagenta },
        { Color16::DarkMagenta, Color16::DarkCyan },
        { Color16::DarkMagenta, Color16::DarkGray },
        { Color16::DarkCyan, Color16::Black },
        { Color16::DarkCyan, Color16::DarkRed },
        { Color16::DarkCyan, Color16::DarkGreen },
        { Color16::DarkCyan, Color16::DarkYellow },
        { Color16::DarkCyan, Color16::DarkBlue },
        { Color16::DarkCyan, Color16::DarkMagenta },
        { Color16::DarkCyan, Color16::DarkCyan },
        { Color16::DarkCyan, Color16::DarkGray },
        { Color16::LightGray, Color16::Black },
        { Color16::LightGray, Color16::DarkRed },
        { Color16::LightGray, Color16::DarkGreen },
        { Color16::LightGray, Color16::DarkYellow },
        { Color16::LightGray, Color16::DarkBlue },
        { Color16::LightGray, Color16::DarkMagenta },
        { Color16::LightGray, Color16::DarkCyan },
        { Color16::LightGray, Color16::DarkGray },
        { Color16::DarkGray, Color16::Black },
        { Color16::DarkGray, Color16::DarkRed },
        { Color16::DarkGray, Color16::DarkGreen },
        { Color16::DarkGray, Color16::DarkYellow },
        { Color16::DarkGray, Color16::DarkBlue },
        { Color16::DarkGray, Color16::DarkMagenta },
        { Color16::DarkGray, Color16::DarkCyan },
        { Color16::DarkGray, Color16::DarkGray },
        { Color16::Red, Color16::Black },
        { Color16::Red, Color16::DarkRed },
        { Color16::Red, Color16::DarkGreen },
        { Color16::Red, Color16::DarkYellow },
        { Color16::Red, Color16::DarkBlue },
        { Color16::Red, Color16::DarkMagenta },
        { Color16::Red, Color16::DarkCyan },
        { Color16::Red, Color16::DarkGray },
        { Color16::Green, Color16::Black },
        { Color16::Green, Color16::DarkRed },
        { Color16::Green, Color16::DarkGreen },
        { Color16::Green, Color16::DarkYellow },
        { Color16::Green, Color16::DarkBlue },
        { Color16::Green, Color16::DarkMagenta },
        { Color16::Green, Color16::DarkCyan },
        { Color16::Green, Color16::DarkGray },
        { Color16::Yellow, Color16::Black },
        { Color16::Yellow, Color16::DarkRed },
        { Color16::Yellow, Color16::DarkGreen },
        { Color16::Yellow, Color16::DarkYellow },
        { Color16::Yellow, Color16::DarkBlue },
        { Color16::Yellow, Color16::DarkMagenta },
        { Color16::Yellow, Color16::DarkCyan },
        { Color16::Yellow, Color16::DarkGray },
        { Color16::Blue, Color16::Black },
        { Color16::Blue, Color16::DarkRed },
        { Color16::Blue, Color16::DarkGreen },
        { Color16::Blue, Color16::DarkYellow },
        { Color16::Blue, Color16::DarkBlue },
        { Color16::Blue, Color16::DarkMagenta },
        { Color16::Blue, Color16::DarkCyan },
        { Color16::Blue, Color16::DarkGray },
        { Color16::Magenta, Color16::Black },
        { Color16::Magenta, Color16::DarkRed },
        { Color16::Magenta, Color16::DarkGreen },
        { Color16::Magenta, Color16::DarkYellow },
        { Color16::Magenta, Color16::DarkBlue },
        { Color16::Magenta, Color16::DarkMagenta },
        { Color16::Magenta, Color16::DarkCyan },
        { Color16::Magenta, Color16::DarkGray },
        { Color16::Cyan, Color16::Black },
        { Color16::Cyan, Color16::DarkRed },
        { Color16::Cyan, Color16::DarkGreen },
        { Color16::Cyan, Color16::DarkYellow },
        { Color16::Cyan, Color16::DarkBlue },
        { Color16::Cyan, Color16::DarkMagenta },
        { Color16::Cyan, Color16::DarkCyan },
        { Color16::Cyan, Color16::DarkGray },
        { Color16::White, Color16::Black },
        { Color16::White, Color16::DarkRed },
        { Color16::White, Color16::DarkGreen },
        { Color16::White, Color16::DarkYellow },
        { Color16::White, Color16::DarkBlue },
        { Color16::White, Color16::DarkMagenta },
        { Color16::White, Color16::DarkCyan },
        { Color16::White, Color16::DarkGray },
      }
    },
    { WallBasicType::OtherLight,
      {
        { Color16::Black, Color16::LightGray },
        { Color16::Black, Color16::Red },
        { Color16::Black, Color16::Green },
        { Color16::Black, Color16::Yellow },
        { Color16::Black, Color16::Blue },
        { Color16::Black, Color16::Magenta },
        { Color16::Black, Color16::Cyan },
        { Color16::Black, Color16::White },
        { Color16::DarkRed, Color16::LightGray },
        { Color16::DarkRed, Color16::Red },
        { Color16::DarkRed, Color16::Green },
        { Color16::DarkRed, Color16::Yellow },
        { Color16::DarkRed, Color16::Blue },
        { Color16::DarkRed, Color16::Magenta },
        { Color16::DarkRed, Color16::Cyan },
        { Color16::DarkRed, Color16::White },
        { Color16::DarkGreen, Color16::LightGray },
        { Color16::DarkGreen, Color16::Red },
        { Color16::DarkGreen, Color16::Green },
        { Color16::DarkGreen, Color16::Yellow },
        { Color16::DarkGreen, Color16::Blue },
        { Color16::DarkGreen, Color16::Magenta },
        { Color16::DarkGreen, Color16::Cyan },
        { Color16::DarkGreen, Color16::White },
        { Color16::DarkYellow, Color16::LightGray },
        { Color16::DarkYellow, Color16::Red },
        { Color16::DarkYellow, Color16::Green },
        { Color16::DarkYellow, Color16::Yellow },
        { Color16::DarkYellow, Color16::Blue },
        { Color16::DarkYellow, Color16::Magenta },
        { Color16::DarkYellow, Color16::Cyan },
        { Color16::DarkYellow, Color16::White },
        { Color16::DarkBlue, Color16::LightGray },
        { Color16::DarkBlue, Color16::Red },
        { Color16::DarkBlue, Color16::Green },
        { Color16::DarkBlue, Color16::Yellow },
        { Color16::DarkBlue, Color16::Blue },
        { Color16::DarkBlue, Color16::Magenta },
        { Color16::DarkBlue, Color16::Cyan },
        { Color16::DarkBlue, Color16::White },
        { Color16::DarkMagenta, Color16::LightGray },
        { Color16::DarkMagenta, Color16::Red },
        { Color16::DarkMagenta, Color16::Green },
        { Color16::DarkMagenta, Color16::Yellow },
        { Color16::DarkMagenta, Color16::Blue },
        { Color16::DarkMagenta, Color16::Magenta },
        { Color16::DarkMagenta, Color16::Cyan },
        { Color16::DarkMagenta, Color16::White },
        { Color16::DarkCyan, Color16::LightGray },
        { Color16::DarkCyan, Color16::Red },
        { Color16::DarkCyan, Color16::Green },
        { Color16::DarkCyan, Color16::Yellow },
        { Color16::DarkCyan, Color16::Blue },
        { Color16::DarkCyan, Color16::Magenta },
        { Color16::DarkCyan, Color16::Cyan },
        { Color16::DarkCyan, Color16::White },
        { Color16::LightGray, Color16::LightGray },
        { Color16::LightGray, Color16::Red },
        { Color16::LightGray, Color16::Green },
        { Color16::LightGray, Color16::Yellow },
        { Color16::LightGray, Color16::Blue },
        { Color16::LightGray, Color16::Magenta },
        { Color16::LightGray, Color16::Cyan },
        { Color16::LightGray, Color16::White },
        { Color16::DarkGray, Color16::LightGray },
        { Color16::DarkGray, Color16::Red },
        { Color16::DarkGray, Color16::Green },
        { Color16::DarkGray, Color16::Yellow },
        { Color16::DarkGray, Color16::Blue },
        { Color16::DarkGray, Color16::Magenta },
        { Color16::DarkGray, Color16::Cyan },
        { Color16::DarkGray, Color16::White },
        { Color16::Red, Color16::LightGray },
        { Color16::Red, Color16::Red },
        { Color16::Red, Color16::Green },
        { Color16::Red, Color16::Yellow },
        { Color16::Red, Color16::Blue },
        { Color16::Red, Color16::Magenta },
        { Color16::Red, Color16::Cyan },
        { Color16::Red, Color16::White },
        { Color16::Green, Color16::LightGray },
        { Color16::Green, Color16::Red },
        { Color16::Green, Color16::Green },
        { Color16::Green, Color16::Yellow },
        { Color16::Green, Color16::Blue },
        { Color16::Green, Color16::Magenta },
        { Color16::Green, Color16::Cyan },
        { Color16::Green, Color16::White },
        { Color16::Yellow, Color16::LightGray },
        { Color16::Yellow, Color16::Red },
        { Color16::Yellow, Color16::Green },
        { Color16::Yellow, Color16::Yellow },
        { Color16::Yellow, Color16::Blue },
        { Color16::Yellow, Color16::Magenta },
        { Color16::Yellow, Color16::Cyan },
        { Color16::Yellow, Color16::White },
        { Color16::Blue, Color16::LightGray },
        { Color16::Blue, Color16::Red },
        { Color16::Blue, Color16::Green },
        { Color16::Blue, Color16::Yellow },
        { Color16::Blue, Color16::Blue },
        { Color16::Blue, Color16::Magenta },
        { Color16::Blue, Color16::Cyan },
        { Color16::Blue, Color16::White },
        { Color16::Magenta, Color16::LightGray },
        { Color16::Magenta, Color16::Red },
        { Color16::Magenta, Color16::Green },
        { Color16::Magenta, Color16::Yellow },
        { Color16::Magenta, Color16::Blue },
        { Color16::Magenta, Color16::Magenta },
        { Color16::Magenta, Color16::Cyan },
        { Color16::Magenta, Color16::White },
        { Color16::Cyan, Color16::LightGray },
        { Color16::Cyan, Color16::Red },
        { Color16::Cyan, Color16::Green },
        { Color16::Cyan, Color16::Yellow },
        { Color16::Cyan, Color16::Blue },
        { Color16::Cyan, Color16::Magenta },
        { Color16::Cyan, Color16::Cyan },
        { Color16::Cyan, Color16::White },
        { Color16::White, Color16::LightGray },
        { Color16::White, Color16::Red },
        { Color16::White, Color16::Green },
        { Color16::White, Color16::Yellow },
        { Color16::White, Color16::Blue },
        { Color16::White, Color16::Magenta },
        { Color16::White, Color16::Cyan },
        { Color16::White, Color16::White },
      }
    },
    { WallBasicType::OtherDark,
      {
        { Color16::Black, Color16::Black },
        { Color16::Black, Color16::DarkRed },
        { Color16::Black, Color16::DarkGreen },
        { Color16::Black, Color16::DarkYellow },
        { Color16::Black, Color16::DarkBlue },
        { Color16::Black, Color16::DarkMagenta },
        { Color16::Black, Color16::DarkCyan },
        { Color16::Black, Color16::DarkGray },
        { Color16::DarkRed, Color16::Black },
        { Color16::DarkRed, Color16::DarkRed },
        { Color16::DarkRed, Color16::DarkGreen },
        { Color16::DarkRed, Color16::DarkYellow },
        { Color16::DarkRed, Color16::DarkBlue },
        { Color16::DarkRed, Color16::DarkMagenta },
        { Color16::DarkRed, Color16::DarkCyan },
        { Color16::DarkRed, Color16::DarkGray },
        { Color16::DarkGreen, Color16::Black },
        { Color16::DarkGreen, Color16::DarkRed },
        { Color16::DarkGreen, Color16::DarkGreen },
        { Color16::DarkGreen, Color16::DarkYellow },
        { Color16::DarkGreen, Color16::DarkBlue },
        { Color16::DarkGreen, Color16::DarkMagenta },
        { Color16::DarkGreen, Color16::DarkCyan },
        { Color16::DarkGreen, Color16::DarkGray },
        { Color16::DarkYellow, Color16::Black },
        { Color16::DarkYellow, Color16::DarkRed },
        { Color16::DarkYellow, Color16::DarkGreen },
        { Color16::DarkYellow, Color16::DarkYellow },
        { Color16::DarkYellow, Color16::DarkBlue },
        { Color16::DarkYellow, Color16::DarkMagenta },
        { Color16::DarkYellow, Color16::DarkCyan },
        { Color16::DarkYellow, Color16::DarkGray },
        { Color16::DarkBlue, Color16::Black },
        { Color16::DarkBlue, Color16::DarkRed },
        { Color16::DarkBlue, Color16::DarkGreen },
        { Color16::DarkBlue, Color16::DarkYellow },
        { Color16::DarkBlue, Color16::DarkBlue },
        { Color16::DarkBlue, Color16::DarkMagenta },
        { Color16::DarkBlue, Color16::DarkCyan },
        { Color16::DarkBlue, Color16::DarkGray },
        { Color16::DarkMagenta, Color16::Black },
        { Color16::DarkMagenta, Color16::DarkRed },
        { Color16::DarkMagenta, Color16::DarkGreen },
        { Color16::DarkMagenta, Color16::DarkYellow },
        { Color16::DarkMagenta, Color16::DarkBlue },
        { Color16::DarkMagenta, Color16::DarkMagenta },
        { Color16::DarkMagenta, Color16::DarkCyan },
        { Color16::DarkMagenta, Color16::DarkGray },
        { Color16::DarkCyan, Color16::Black },
        { Color16::DarkCyan, Color16::DarkRed },
        { Color16::DarkCyan, Color16::DarkGreen },
        { Color16::DarkCyan, Color16::DarkYellow },
        { Color16::DarkCyan, Color16::DarkBlue },
        { Color16::DarkCyan, Color16::DarkMagenta },
        { Color16::DarkCyan, Color16::DarkCyan },
        { Color16::DarkCyan, Color16::DarkGray },
        { Color16::LightGray, Color16::Black },
        { Color16::LightGray, Color16::DarkRed },
        { Color16::LightGray, Color16::DarkGreen },
        { Color16::LightGray, Color16::DarkYellow },
        { Color16::LightGray, Color16::DarkBlue },
        { Color16::LightGray, Color16::DarkMagenta },
        { Color16::LightGray, Color16::DarkCyan },
        { Color16::LightGray, Color16::DarkGray },
        { Color16::DarkGray, Color16::Black },
        { Color16::DarkGray, Color16::DarkRed },
        { Color16::DarkGray, Color16::DarkGreen },
        { Color16::DarkGray, Color16::DarkYellow },
        { Color16::DarkGray, Color16::DarkBlue },
        { Color16::DarkGray, Color16::DarkMagenta },
        { Color16::DarkGray, Color16::DarkCyan },
        { Color16::DarkGray, Color16::DarkGray },
        { Color16::Red, Color16::Black },
        { Color16::Red, Color16::DarkRed },
        { Color16::Red, Color16::DarkGreen },
        { Color16::Red, Color16::DarkYellow },
        { Color16::Red, Color16::DarkBlue },
        { Color16::Red, Color16::DarkMagenta },
        { Color16::Red, Color16::DarkCyan },
        { Color16::Red, Color16::DarkGray },
        { Color16::Green, Color16::Black },
        { Color16::Green, Color16::DarkRed },
        { Color16::Green, Color16::DarkGreen },
        { Color16::Green, Color16::DarkYellow },
        { Color16::Green, Color16::DarkBlue },
        { Color16::Green, Color16::DarkMagenta },
        { Color16::Green, Color16::DarkCyan },
        { Color16::Green, Color16::DarkGray },
        { Color16::Yellow, Color16::Black },
        { Color16::Yellow, Color16::DarkRed },
        { Color16::Yellow, Color16::DarkGreen },
        { Color16::Yellow, Color16::DarkYellow },
        { Color16::Yellow, Color16::DarkBlue },
        { Color16::Yellow, Color16::DarkMagenta },
        { Color16::Yellow, Color16::DarkCyan },
        { Color16::Yellow, Color16::DarkGray },
        { Color16::Blue, Color16::Black },
        { Color16::Blue, Color16::DarkRed },
        { Color16::Blue, Color16::DarkGreen },
        { Color16::Blue, Color16::DarkYellow },
        { Color16::Blue, Color16::DarkBlue },
        { Color16::Blue, Color16::DarkMagenta },
        { Color16::Blue, Color16::DarkCyan },
        { Color16::Blue, Color16::DarkGray },
        { Color16::Magenta, Color16::Black },
        { Color16::Magenta, Color16::DarkRed },
        { Color16::Magenta, Color16::DarkGreen },
        { Color16::Magenta, Color16::DarkYellow },
        { Color16::Magenta, Color16::DarkBlue },
        { Color16::Magenta, Color16::DarkMagenta },
        { Color16::Magenta, Color16::DarkCyan },
        { Color16::Magenta, Color16::DarkGray },
        { Color16::Cyan, Color16::Black },
        { Color16::Cyan, Color16::DarkRed },
        { Color16::Cyan, Color16::DarkGreen },
        { Color16::Cyan, Color16::DarkYellow },
        { Color16::Cyan, Color16::DarkBlue },
        { Color16::Cyan, Color16::DarkMagenta },
        { Color16::Cyan, Color16::DarkCyan },
        { Color16::Cyan, Color16::DarkGray },
        { Color16::White, Color16::Black },
        { Color16::White, Color16::DarkRed },
        { Color16::White, Color16::DarkGreen },
        { Color16::White, Color16::DarkYellow },
        { Color16::White, Color16::DarkBlue },
        { Color16::White, Color16::DarkMagenta },
        { Color16::White, Color16::DarkCyan },
        { Color16::White, Color16::DarkGray },
      }
    },
  };
  
  inline std::vector<Color> key_fg_palette
  {
    Color16::Black,
    Color16::DarkRed,
    Color16::DarkGreen,
    Color16::DarkYellow,
    Color16::DarkBlue,
    Color16::DarkMagenta,
    Color16::DarkCyan,
    Color16::LightGray,
    Color16::DarkGray,
    Color16::Red,
    Color16::Green,
    Color16::Yellow,
    Color16::Blue,
    Color16::Magenta,
    Color16::Cyan,
    Color16::White,
  };
  
  inline std::vector<Color> potion_fg_palette
  {
    Color16::Black,
    Color16::DarkRed,
    Color16::DarkGreen,
    Color16::DarkYellow,
    Color16::DarkBlue,
    Color16::DarkMagenta,
    Color16::DarkCyan,
    Color16::LightGray,
    Color16::DarkGray,
    Color16::Red,
    Color16::Green,
    Color16::Yellow,
    Color16::Blue,
    Color16::Magenta,
    Color16::Cyan,
    Color16::White,
  };
  
  inline std::vector<Color> crossbow_fg_palette
  {
    Color16::DarkBlue,
    Color16::DarkCyan,
    Color16::LightGray,
    Color16::DarkGray,
    Color16::Blue,
    Color16::Cyan,
  };
}
