name: build ubuntu

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-demo:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3
      
      # Step 2: Move to the parent directory and fetch dependencies
      - name: Fetch dependencies
        run: |
          cd ..
          git clone https://github.com/razterizer/Core.git
          git clone https://github.com/razterizer/Termin8or.git
          # git clone https://github.com/razterizer/8Beat.git
          # git clone https://github.com/razterizer/AudioLibSwitcher_OpenAL.git --recurse-submodules

      # # Step 3: Install OpenAL
      # - name: Install OpenAL
      #   run: sudo apt install libopenal-dev
      
      # Step 3: Change to the correct directory and build
      - name: Build project
        run: |
          cd demo
          ./build_demo.sh
        continue-on-error: false # Ensure errors are not bypassed
      
      # Step 4: Install scc
      - name: Install scc
        run: |
          SCC_VERSION=$(curl -s https://api.github.com/repos/boyter/scc/releases/latest | jq -r '.tag_name')
          curl -L -o scc.tar.gz https://github.com/boyter/scc/releases/download/${SCC_VERSION}/scc-x86_64-unknown-linux-gnu.tar.gz
          tar -xzf scc.tar.gz
          chmod +x scc
          sudo mv scc /usr/local/bin/

      # Step 5: Run scc and create badge
      - name: Count C++ LOC and generate badge
        run: |
          mkdir -p loc-badge
          scc --include-ext cpp,hpp --output json > loc-badge/raw.json

          LOC=$(jq '[.[] | select(.language=="C++") | .code] | add' loc-badge/raw.json)

          cat <<EOF > loc-badge/loc-badge.json
          {
            "schemaVersion": 1,
            "label": "C++ LOC",
            "message": "${LOC} lines",
            "color": "blue"
          }
          EOF

      # Step 6: Push badge to gh-pages
      - name: Publish badge to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: loc-badge
          publish_branch: gh-pages
          force_orphan: true

  
